spring.application.name=backendTprints
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/tprints
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave JWT en Base64. Esta clave es de desarrollo.
# Luego puedes cambiarla por una variable de entorno.
jwt.secret=VGhpc0lzQVRwcmludHNTZWNyZXRLZXlGb3JEZXZlbG9wbWVudDEyMzQ1Njc4OTA=
jwt.expiration-ms=86400000