spring.application.name=tprints-backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d89m108jo6nc73dvrkf0-a.oregon-postgres.render.com:5432/tprints?sslmode=require
spring.datasource.username=postgres1
spring.datasource.password=W6w8mmpeHVpK89DKW45AYF7daAcoIiHC
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:VGhpc0lzQVRwcmludHNTZWNyZXRLZXlGb3JEZXZlbG9wbWVudDEyMzQ1Njc4OTA=}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}





